name: Deploy a GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inyectar clave de la IA
        run: sed -i "s/CLAVE_GEMINI/${{ secrets.GEMINI_API_KEY }}/g" asistente.html

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir el sitio
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Desplegar
        id: deployment
        uses: actions/deploy-pages@v4
